# Generated by Django 4.2 on 2025-04-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Food', 'Food'), ('Health & Fitness', 'Health & Fitness'), ('Debt Payments', 'Debt Payments'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Personal Care', 'Personal Care'), ('Savings & Investments', 'Savings & Investments'), ('Gifts & Donations', 'Gifts & Donations'), ('Travel', 'Travel'), ('Subscriptions', 'Subscriptions'), ('Miscellaneous', 'Miscellaneous')], max_length=255),
        ),
    ]
