# Generated by Django 4.2 on 2025-04-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Food', 'Food'), ('Health & Fitness', 'Health & Fitness'), ('Debt Payments', 'Debt Payments'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Personal Care', 'Personal Care'), ('Savings & Investments', 'Savings & Investments'), ('Gifts & Donations', 'Gifts & Donations'), ('Travel', 'Travel'), ('Subscriptions', 'Subscriptions'), ('Miscellaneous', 'Miscellaneous'), ('Loan Payments', 'Loan Payments'), ('Bad Debt', 'Bad Debt'), ('Fees', 'Fees'), ('Taxes', 'Taxes'), ('Insurance', 'Insurance'), ('Other', 'Other')], max_length=50),
        ),
    ]
