# Generated by Django 4.2 on 2025-04-26 00:24

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Sources',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Bonus', 'Bonus'), ('Overtime', 'Overtime'), ('Commission', 'Commission'), ('Business Revenue', 'Business Revenue'), ('Product Sales', 'Product Sales'), ('Service Income', 'Service Income'), ('Investment Returns', 'Investment Returns'), ('Project Payment', 'Project Payment'), ('Client Payment', 'Client Payment'), ('Gig Income', 'Gig Income'), ('Allowance', 'Allowance'), ('Miscellaneous', 'Miscellaneous'), ('Gifts', 'Gifts'), ('Grants', 'Grants')], default='Salary', max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='IncomeCategory',
        ),
        migrations.DeleteModel(
            name='ProfileType',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
