# Generated by Django 4.2 on 2025-04-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_source_remove_userprofile_profile_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Bonus', 'Bonus'), ('Overtime', 'Overtime'), ('Commission', 'Commission'), ('Business Revenue', 'Business Revenue'), ('Product Sales', 'Product Sales'), ('Service Income', 'Service Income'), ('Investment Returns', 'Investment Returns'), ('Project Payment', 'Project Payment'), ('Client Payment', 'Client Payment'), ('Gig Income', 'Gig Income'), ('Allowance', 'Allowance'), ('Miscellaneous', 'Miscellaneous'), ('Gifts', 'Gifts'), ('Grants', 'Grants')], max_length=50),
        ),
    ]
