# Generated by Django 4.2 on 2025-04-29 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
