# Generated by Django 4.2 on 2025-05-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDash', '0002_alter_target_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='period',
            field=models.CharField(choices=[('daily', 'Day'), ('weekly', 'Week'), ('monthly', 'Month'), ('yearly', 'Year')], max_length=10),
        ),
    ]
